name: Go Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - name: Install dependencies
        run: go get .
      - name: Unit Test
        run: |
          make import-gpgkeys-for-test
          make test
      - name: Build
        run: |
          make build
          ./kubesec help
      - name: goreleaser snapshot
        run: |
          go install github.com/goreleaser/goreleaser@latest
          goreleaser release --snapshot --clean
